name: Generate Snake Grid

on:
  schedule:
    - cron: "0 0 * * *" # Generate every midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Generate Snake ğŸ
        uses: Platane/snk@v3
        with:
          github_user_name: ramjam97
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Upload to GitHub ğŸš€
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
